name: print_slayer
description: A simple dart package for removing all print() and debugPrint() statements from your code.
version: 1.1.0
repository: https://github.com/DevPrinceK/print_slayer
homepage: https://github.com/DevPrinceK/print_slayer

environment:
  sdk: ^3.0.6

dependencies:
  path: ^1.8.3
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

topics:
  - cleancode
  - print-remover
  - debugging
  - dart
